---
default:
  app:
    name: Boilermaker
    version: 1.0.0
    support_email: support@example.com
  features:
    user_registration: true
    personal_accounts: false
  security:
    require_two_factor_authentication: false
  ui:
    typography:
      uppercase: true
      size: base
development:
  app:
    name: Boilermaker
    version: 1.0.0
    support_email: support@example.com
    description: A modern Rails application
  features:
    user_registration: true
    personal_accounts: true
  security:
    require_two_factor_authentication: false
  ui:
    theme:
      light: drafting-table
      dark: dim
    navigation:
      layout_mode: sidebar
    typography:
      font: JetBrains Mono
      uppercase: true
      size: dense
test:
  security:
    require_two_factor_authentication: false
